import type { ControlDefinition, PanelDefinition } from './controls';

/**
 * The nine configurator panels.
 *
 * Order matters: this is the order the sidebar renders, and it runs from "change everything at
 * once" to "change one thing precisely". Presets first is not decoration — it is the difference
 * between a configurator that ships a good-looking site in a minute and one that ships a
 * default-looking site because nobody dared touch the sliders.
 */

const presetsPanel: PanelDefinition = {
  id: 'presets',
  title: 'Presets',
  summary:
    'Ten complete looks. Previewed first, applied only when you say so, undone in one click.',
  presets: [
    'gulf-premium',
    'nordic-calm',
    'campus-bright',
    'editorial-serif',
    'boutique-mono',
    'test-prep-bold',
    'heritage-warm',
    'metro-contrast',
    'coastal-soft',
    'midnight-focus',
  ],
  controls: [
    {
      id: 'preset-active',
      label: 'Active preset',
      kind: 'preset',
      path: 'preset',
      help: 'Applying a preset takes a snapshot first, so undo restores exactly what you had.',
      sample: 'palette',
      keywords: ['look', 'style', 'theme', 'starter'],
    },
    {
      id: 'preset-export',
      label: 'Export current look as a preset',
      kind: 'text',
      path: 'presetExportName',
      help: 'Saves the whole current configuration under a name you can import on another site.',
      isAdvanced: true,
      keywords: ['save', 'share', 'json', 'backup'],
    },
  ],
};

const colorsPanel: PanelDefinition = {
  id: 'colors',
  title: 'Colors',
  summary: 'One accent drives the whole palette. Every derived colour is checked for contrast.',
  presets: ['ocean', 'forest', 'plum', 'ember', 'slate'],
  controls: [
    {
      id: 'accent',
      label: 'Accent',
      kind: 'accent',
      path: 'accent',
      help: 'Pick from 24 curated accents or enter your own hex. Custom hexes are reviewed per mode.',
      sample: 'palette',
      overridable: true,
      keywords: ['brand', 'primary', 'colour', 'hex'],
    },
    {
      id: 'accent-custom',
      label: 'Custom accent hex',
      kind: 'color',
      path: 'customAccent',
      help: 'Overrides the curated accent. We show you the nearest compliant colour if yours falls short.',
      sample: 'palette',
      keywords: ['hex', 'brand colour'],
    },
    {
      id: 'default-mode',
      label: 'Default mode',
      kind: 'select',
      path: 'defaultMode',
      help: 'What a first-time visitor sees before they choose. Auto follows their system setting.',
      keywords: ['dark', 'light', 'auto', 'scheme'],
    },
    {
      id: 'accent-as-text',
      label: 'Use accent for text links',
      kind: 'toggle',
      path: 'accentAsText',
      help: 'Off uses a darkened variant that always clears 4.5:1 on body backgrounds.',
      isAdvanced: true,
      keywords: ['link', 'contrast', 'wcag'],
    },
    {
      id: 'neutral-warmth',
      label: 'Neutral warmth',
      kind: 'range',
      path: 'neutralWarmth',
      help: 'Shifts the greys towards warm or cool without changing their lightness.',
      isAdvanced: true,
      keywords: ['grey', 'gray', 'temperature'],
    },
    {
      id: 'admin-mode',
      label: 'Admin appearance',
      kind: 'select',
      path: 'adminMode',
      help: 'The dashboard follows its own light or dark choice, independent of the public site.',
      isAdvanced: true,
      keywords: ['dashboard', 'wp-admin', 'dark mode'],
    },
  ],
};

const typographyPanel: PanelDefinition = {
  id: 'typography',
  title: 'Typography',
  summary: 'Ten curated pairings, or set each role yourself. Everything is self-hosted.',
  presets: ['editorial', 'geometric', 'humanist', 'academic', 'neo-grotesque'],
  controls: [
    {
      id: 'font-pairing',
      label: 'Font pairing',
      kind: 'font',
      path: 'typography.pairing',
      help: 'Sets heading and body together. Change a single role below to break the pairing.',
      sample: 'type-specimen',
      keywords: ['font', 'family', 'typeface', 'pairing'],
    },
    {
      id: 'font-heading',
      label: 'Heading font',
      kind: 'font',
      path: 'typography.overrides.heading',
      help: 'Leave unset to follow the pairing. Setting it here breaks inheritance for headings only.',
      sample: 'type-specimen',
      overridable: true,
      keywords: ['h1', 'title', 'display'],
    },
    {
      id: 'font-body',
      label: 'Body font',
      kind: 'font',
      path: 'typography.overrides.body',
      help: 'Leave unset to follow the pairing.',
      sample: 'type-specimen',
      overridable: true,
      keywords: ['paragraph', 'text', 'copy'],
    },
    {
      id: 'base-size',
      label: 'Base size',
      kind: 'number',
      path: 'typography.baseSize',
      help: 'The size body text lands at on a desktop. Everything else scales from it.',
      sample: 'type-specimen',
      keywords: ['rem', 'px', 'size'],
    },
    {
      id: 'scale-ratio',
      label: 'Scale ratio',
      kind: 'range',
      path: 'typography.scaleRatio',
      help: 'How fast headings grow. The mobile ratio is damped automatically so H1 stays readable.',
      isAdvanced: true,
      keywords: ['modular', 'ratio', 'hierarchy'],
    },
    {
      id: 'font-mono',
      label: 'Monospace font',
      kind: 'font',
      path: 'typography.overrides.mono',
      help: 'Used in code samples and the CSV import preview.',
      isAdvanced: true,
      sample: 'type-specimen',
      overridable: true,
      keywords: ['code', 'fixed width'],
    },
    {
      id: 'font-subsets',
      label: 'Character subsets',
      kind: 'select',
      path: 'typography.subsets',
      help: 'Latin only keeps fonts small. Add Arabic or Bengali if you publish in those scripts.',
      isAdvanced: true,
      keywords: ['arabic', 'bengali', 'latin', 'language', 'rtl'],
    },
  ],
};

const patternsPanel: PanelDefinition = {
  id: 'patterns',
  title: 'Patterns',
  summary:
    'Twenty-eight tileable patterns, tinted with your accent, at separate light and dark opacities.',
  presets: ['none', 'subtle-grid', 'soft-dots', 'diagonal-weave', 'topographic'],
  controls: [
    {
      id: 'pattern',
      label: 'Pattern',
      kind: 'pattern',
      path: 'pattern.id',
      help: 'Tiles behind hero and section backgrounds. Rendered as an inline data URI — no extra request.',
      sample: 'pattern-tile',
      overridable: true,
      keywords: ['texture', 'background', 'tile'],
    },
    {
      id: 'pattern-opacity-light',
      label: 'Opacity in light mode',
      kind: 'range',
      path: 'pattern.lightOpacity',
      help: 'A pattern that reads well on white is usually invisible on near-black, hence two values.',
      sample: 'pattern-tile',
      overridable: true,
      keywords: ['transparency', 'strength'],
    },
    {
      id: 'pattern-opacity-dark',
      label: 'Opacity in dark mode',
      kind: 'range',
      path: 'pattern.darkOpacity',
      help: 'Set independently of light mode.',
      sample: 'pattern-tile',
      overridable: true,
      keywords: ['transparency', 'strength', 'dark'],
    },
    {
      id: 'pattern-scale',
      label: 'Tile scale',
      kind: 'range',
      path: 'pattern.scale',
      help: 'Larger tiles read as texture, smaller as noise.',
      isAdvanced: true,
      sample: 'pattern-tile',
    },
    {
      id: 'pattern-blend',
      label: 'Blend mode',
      kind: 'select',
      path: 'pattern.blend',
      help: 'Multiply darkens, overlay keeps contrast. Normal is safest over photography.',
      isAdvanced: true,
      keywords: ['multiply', 'overlay', 'screen'],
    },
    {
      id: 'pattern-attachment',
      label: 'Attachment',
      kind: 'select',
      path: 'pattern.attachment',
      help: 'Fixed makes the pattern sit still while the page scrolls. Ignored on touch devices.',
      isAdvanced: true,
      keywords: ['parallax', 'fixed', 'scroll'],
    },
  ],
};

const layoutPanel: PanelDefinition = {
  id: 'layout',
  title: 'Layout',
  summary: 'Width, density and corner treatment. These three do most of the work of a redesign.',
  presets: ['comfortable', 'compact', 'spacious'],
  controls: [
    {
      id: 'container-width',
      label: 'Content width',
      kind: 'number',
      path: 'layout.containerWidth',
      help: 'The maximum line length for body content. Wider is not better past about 75 characters.',
      overridable: true,
      keywords: ['container', 'max width', 'measure'],
    },
    {
      id: 'density',
      label: 'Density',
      kind: 'select',
      path: 'layout.density',
      help: 'Scales every spacing token at once. Compact suits data-heavy pages, spacious suits marketing.',
      overridable: true,
      keywords: ['spacing', 'padding', 'whitespace'],
    },
    {
      id: 'radius',
      label: 'Corner radius',
      kind: 'range',
      path: 'layout.radius',
      help: 'Applies to cards, buttons and inputs together so they stay a family.',
      overridable: true,
      keywords: ['rounded', 'border radius', 'corners'],
    },
    {
      id: 'section-spacing',
      label: 'Section spacing',
      kind: 'range',
      path: 'layout.sectionSpacing',
      help: 'The vertical rhythm between page sections.',
      isAdvanced: true,
      overridable: true,
    },
    {
      id: 'grid-gutter',
      label: 'Grid gutter',
      kind: 'range',
      path: 'layout.gutter',
      help: 'The gap between columns in card grids.',
      isAdvanced: true,
    },
    {
      id: 'shadow-strength',
      label: 'Shadow strength',
      kind: 'range',
      path: 'layout.shadowStrength',
      help: 'Zero gives a flat look that stays legible in dark mode without tuning.',
      isAdvanced: true,
      keywords: ['elevation', 'depth'],
    },
  ],
};

const motionPanel: PanelDefinition = {
  id: 'motion',
  title: 'Motion',
  summary: 'Five presets, seventeen individual effects. Everything obeys reduced-motion.',
  presets: ['none', 'subtle', 'balanced', 'expressive', 'cinematic'],
  controls: [
    {
      id: 'motion-preset',
      label: 'Motion preset',
      kind: 'select',
      path: 'motion.preset',
      help: 'Sets every duration and easing at once. Replay the sample to see the difference.',
      sample: 'motion-card',
      keywords: ['animation', 'transition', 'speed'],
    },
    {
      id: 'motion-easing',
      label: 'Easing',
      kind: 'select',
      path: 'motion.easing',
      help: 'Six named curves, or write your own bezier below.',
      sample: 'motion-card',
      keywords: ['curve', 'ease', 'timing'],
    },
    {
      id: 'motion-effects',
      label: 'Effects',
      kind: 'select',
      path: 'motion.effects',
      help: 'Each effect loads its own module. Turning one off removes its JavaScript entirely.',
      sample: 'motion-card',
      keywords: ['reveal', 'parallax', 'counter', 'marquee'],
    },
    {
      id: 'motion-custom-bezier',
      label: 'Custom bezier',
      kind: 'bezier',
      path: 'motion.customBezier',
      help: 'Four numbers. Control points outside 0–1 on the x axis are rejected, as CSS requires.',
      isAdvanced: true,
      sample: 'motion-card',
      keywords: ['cubic-bezier', 'curve'],
    },
    {
      id: 'motion-duration-scale',
      label: 'Duration scale',
      kind: 'range',
      path: 'motion.durationScale',
      help: 'Multiplies every duration. Useful for slowing everything down without editing each one.',
      isAdvanced: true,
    },
    {
      id: 'motion-respect-reduced',
      label: 'Respect reduced motion',
      kind: 'toggle',
      path: 'motion.respectReducedMotion',
      help: 'Locked on. Shown so you can see it is on, not so you can turn it off.',
      isAdvanced: true,
      keywords: ['accessibility', 'vestibular', 'prefers-reduced-motion'],
    },
  ],
};

const headerPanel: PanelDefinition = {
  id: 'header',
  title: 'Header',
  summary: 'Six arrangements, a mega-menu, the utility bar and the announcement bar.',
  presets: ['classic', 'centred', 'split', 'stacked', 'minimal', 'transparent-hero'],
  controls: [
    {
      id: 'header-variant',
      label: 'Header variant',
      kind: 'select',
      path: 'header.variant',
      help: 'Changes the arrangement, not the content. Your menu and logo carry across.',
      sample: 'chrome-outline',
      keywords: ['navigation', 'nav', 'menu', 'layout'],
    },
    {
      id: 'header-sticky',
      label: 'Sticky on scroll',
      kind: 'toggle',
      path: 'header.sticky',
      help: 'Keeps the header in view. It shrinks after the first scroll so it costs less height.',
      keywords: ['fixed', 'pinned'],
    },
    {
      id: 'header-utility-bar',
      label: 'Utility bar',
      kind: 'toggle',
      path: 'header.utilityBar',
      help: 'The thin strip above the header for phone, email and office hours.',
      keywords: ['topbar', 'contact'],
    },
    {
      id: 'header-announcement',
      label: 'Announcement bar',
      kind: 'toggle',
      path: 'header.announcement.enabled',
      help: 'Scheduled: it appears and disappears on its own between the dates you set.',
      keywords: ['banner', 'promo', 'notice'],
    },
    {
      id: 'header-announcement-window',
      label: 'Announcement schedule',
      kind: 'text',
      path: 'header.announcement.window',
      help: 'Start and end in site time. Leave the end empty to run until you turn it off.',
      isAdvanced: true,
      keywords: ['date', 'schedule', 'campaign'],
    },
    {
      id: 'header-mega-menu',
      label: 'Mega menu',
      kind: 'toggle',
      path: 'header.megaMenu',
      help: 'Turns top-level items with children into a multi-column panel with featured content.',
      isAdvanced: true,
      keywords: ['dropdown', 'columns'],
    },
    {
      id: 'header-transparent',
      label: 'Transparent over hero',
      kind: 'toggle',
      path: 'header.transparentOverHero',
      help: 'Only where a full-bleed hero follows. Falls back to solid everywhere else automatically.',
      isAdvanced: true,
      overridable: true,
    },
  ],
};

const footerPanel: PanelDefinition = {
  id: 'footer',
  title: 'Footer',
  summary: 'Four arrangements plus the floating action cluster.',
  presets: ['columns', 'compact', 'centred', 'contact-first'],
  controls: [
    {
      id: 'footer-variant',
      label: 'Footer variant',
      kind: 'select',
      path: 'footer.variant',
      help: 'Changes column count and order. Widget content carries across.',
      sample: 'chrome-outline',
      keywords: ['layout', 'columns'],
    },
    {
      id: 'footer-newsletter',
      label: 'Newsletter signup',
      kind: 'toggle',
      path: 'footer.newsletter',
      help: 'Uses the same spam protection and consent handling as every other form.',
      keywords: ['email', 'subscribe', 'mailing list'],
    },
    {
      id: 'footer-actions',
      label: 'Floating actions',
      kind: 'select',
      path: 'footer.floatingActions',
      help: 'WhatsApp, call, back-to-top and book-a-counselling, in the order you choose.',
      keywords: ['whatsapp', 'call', 'fab', 'sticky button'],
    },
    {
      id: 'footer-credit',
      label: 'Footer credit line',
      kind: 'text',
      path: 'footer.credit',
      help: 'Yours to edit or empty. Nothing is hidden behind a licence check.',
      isAdvanced: true,
      keywords: ['copyright', 'branding'],
    },
    {
      id: 'footer-back-to-top',
      label: 'Back to top threshold',
      kind: 'number',
      path: 'footer.backToTopThreshold',
      help: 'How far down the page the button appears, in viewport heights.',
      isAdvanced: true,
    },
  ],
};

const sectionsPanel: PanelDefinition = {
  id: 'sections',
  title: 'Sections',
  summary:
    'Re-theme one section without touching the rest. Anything you do not set here is inherited.',
  presets: ['inherit-all', 'alternating-tone', 'hero-accent', 'quiet-body'],
  controls: [
    {
      id: 'section-target',
      label: 'Section',
      kind: 'select',
      path: 'sections.target',
      help: 'Pick a section to override. The controls below then apply to that section only.',
      keywords: ['hero', 'features', 'testimonials', 'cta'],
    },
    {
      id: 'partner-names',
      label: 'Show partner names',
      kind: 'toggle',
      path: 'chrome.showsPartnerNames',
      help: 'On shows each logo with its name beside it. Off shows the logos alone, larger — good once your partners are recognisable on sight. The names stay readable to screen readers either way.',
      keywords: ['logo', 'logos', 'trusted by', 'accreditation', 'partners', 'caption', 'label'],
    },
    {
      id: 'section-enabled',
      label: 'Show this section',
      kind: 'toggle',
      path: 'sections.override.enabled',
      help: 'Off removes the section from the page entirely — its markup is never rendered, so it costs nothing and is invisible to screen readers. The header and footer cannot be switched off.',
      overridable: true,
      keywords: ['hide', 'show', 'disable', 'enable', 'remove', 'off', 'on', 'visibility'],
    },
    {
      id: 'section-accent',
      label: 'Section accent',
      kind: 'accent',
      path: 'sections.override.accent',
      help: 'Unset means inherit. The Inherit badge shows when a control is following the global value.',
      sample: 'palette',
      overridable: true,
    },
    {
      id: 'section-tone',
      label: 'Background tone',
      kind: 'select',
      path: 'sections.override.tone',
      help: 'Base, raised or sunken. Tones are derived from the palette, never hard-coded.',
      overridable: true,
      keywords: ['background', 'surface'],
    },
    {
      id: 'section-pattern',
      label: 'Section pattern',
      kind: 'pattern',
      path: 'sections.override.pattern',
      help: 'Unset means inherit the global pattern.',
      sample: 'pattern-tile',
      overridable: true,
    },
    {
      id: 'section-density',
      label: 'Section density',
      kind: 'select',
      path: 'sections.override.density',
      help: 'Unset means inherit.',
      isAdvanced: true,
      overridable: true,
    },
    {
      id: 'section-motion',
      label: 'Section motion',
      kind: 'select',
      path: 'sections.override.motion',
      help: 'Unset means inherit. Reduced-motion still wins over anything set here.',
      isAdvanced: true,
      overridable: true,
      sample: 'motion-card',
    },
  ],
};

export const PANELS: readonly PanelDefinition[] = [
  presetsPanel,
  colorsPanel,
  typographyPanel,
  patternsPanel,
  layoutPanel,
  motionPanel,
  headerPanel,
  footerPanel,
  sectionsPanel,
];

export function panelById(id: string): PanelDefinition | undefined {
  return PANELS.find((panel) => panel.id === id);
}

/** Every control in every panel, in panel order. */
export function allControls(): readonly ControlDefinition[] {
  return PANELS.flatMap((panel) => panel.controls);
}
